/ext3/miniforge3/envs/visnet/lib/python3.9/site-packages/lightning_fabric/__init__.py:40: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
wandb: Tracking run with wandb version 0.22.1
wandb: W&B syncing is set to `offline` in this directory. Run `wandb online` or set WANDB_MODE=online to enable cloud syncing.
wandb: Run data is saved locally in /scratch/cz2200/aib9/wandb/offline-run-20251024_230230-2n5fjzek
/ext3/miniforge3/envs/visnet/lib/python3.9/site-packages/torch_geometric/nn/conv/message_passing.py:1032: UserWarning: 'NeighborEmbedding.jittable' is deprecated and a no-op. Please remove its usage.
  warnings.warn(f"'{self.__class__.__name__}.jittable' is deprecated "
/ext3/miniforge3/envs/visnet/lib/python3.9/site-packages/torch_geometric/nn/conv/message_passing.py:1032: UserWarning: 'EdgeEmbedding.jittable' is deprecated and a no-op. Please remove its usage.
  warnings.warn(f"'{self.__class__.__name__}.jittable' is deprecated "
/ext3/miniforge3/envs/visnet/lib/python3.9/site-packages/torch_geometric/nn/conv/message_passing.py:1032: UserWarning: 'ViS_MP_Vertex_Edge.jittable' is deprecated and a no-op. Please remove its usage.
  warnings.warn(f"'{self.__class__.__name__}.jittable' is deprecated "
Original data shape: (1000, 58, 3)
CV shape: (1000, 2)
Using CUDA device: Tesla V100-SXM2-32GB
CUDA memory: 34.1 GB
Successfully initialized bias for log_var outputs to: -3.00

============================================================
Starting Training - 142 samples
Model parameters: 7,287,429
Loss type: MSE (coordinate-based)
============================================================

Traceback (most recent call last):
  File "/scratch/cz2200/aib9/train_vae_equivar.py", line 385, in <module>
    main()
  File "/scratch/cz2200/aib9/train_vae_equivar.py", line 255, in main
    recon_batch, mu, log_var = model(molecules)
  File "/ext3/miniforge3/envs/visnet/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/ext3/miniforge3/envs/visnet/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1568, in _call_impl
    result = forward_call(*args, **kwargs)
  File "/scratch/cz2200/aib9/mse_training/vae_model_new.py", line 66, in forward
    z, v = self.encoder(data)
  File "/ext3/miniforge3/envs/visnet/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/ext3/miniforge3/envs/visnet/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/scratch/cz2200/aib9/mse_training/visnet_vae_encoder_mse.py", line 67, in forward
    x, v = self.output_model.pre_reduce(x, v, data.z, data.pos, data.batch)
ValueError: too many values to unpack (expected 2)
[1;34mwandb[0m: 
[1;34mwandb[0m: You can sync this run to the cloud by running:
[1;34mwandb[0m: [1mwandb sync /scratch/cz2200/aib9/wandb/offline-run-20251024_230230-2n5fjzek[0m
[1;34mwandb[0m: Find logs at: [1;35mwandb/offline-run-20251024_230230-2n5fjzek/logs[0m
